# Generated by Django 5.2.7 on 2025-11-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_kit', models.CharField(max_length=100, unique=True)),
                ('tipo_estacion', models.CharField(blank=True, choices=[('LAPTOP', 'LAPTOP'), ('DESKTOP', 'DESKTOP')], max_length=255, null=True)),
                ('modelo_laptop', models.CharField(blank=True, choices=[('DELL E5500', 'DELL E5500'), ('DELL E5520', 'DELL E5520')], max_length=20, null=True)),
                ('modelo_desktop', models.CharField(blank=True, choices=[('DELL OPTIPLEX 360', 'DELL OPTIPLEX 360'), ('DELL OPTIPLEX 390', 'DELL OPTIPLEX 390')], max_length=20, null=True)),
                ('escaner', models.BooleanField(default=False)),
                ('modelo_escaner', models.CharField(choices=[('Epson 110', 'Epson 110'), ('Epson 100', 'Epson 100')], max_length=20)),
                ('camara', models.BooleanField(default=False)),
                ('modelo_camara', models.CharField(choices=[('Logitech 110', 'Logitech 110'), ('Logitech 150', 'Logitech 150')], max_length=20)),
                ('impresora', models.BooleanField(default=False)),
                ('modelo_impresora', models.CharField(choices=[('HP LPB3000', 'HP LPB3000'), ('HP LPB6000', 'HP LPB6000'), ('CANON 2700', 'CANON 2700'), ('CANON 2900', 'CANON 2900'), ('BROTHER 2700', 'BROTHER 2700')], max_length=20)),
                ('decadactilar', models.BooleanField(default=False)),
                ('extension', models.BooleanField(default=False)),
                ('estabilizador', models.BooleanField(default=False)),
                ('tripode', models.BooleanField(default=False)),
                ('banner', models.BooleanField(default=False)),
                ('pad_firmas', models.BooleanField(default=False)),
                ('hub_usb', models.BooleanField(default=False)),
                ('adaptador_3a2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estacion', models.CharField(max_length=100, unique=True)),
                ('contador_r', models.IntegerField(default=0)),
                ('contador_c', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacion_pdse', models.IntegerField(default=0)),
                ('fecha_certificado_pdse', models.DateField(blank=True)),
                ('fecha_nota', models.DateField(blank=True)),
                ('cite', models.IntegerField(default=0)),
                ('glosa', models.CharField(blank=True, max_length=511)),
                ('tipo_proceso', models.CharField(choices=[('Operador Urbano', 'Operador Urbano'), ('Operador Rural', 'Operador Rural'), ('Soporte Urbano', 'Soporte Urbano'), ('Soporte Rural', 'Soporte Rural'), ('Coordinador', 'Coordinador'), ('Auxiliar Tecnico', 'Auxiliar Tecnico'), ('Logistica', 'Logistica'), ('Asistente Megacentro', 'Asistente Megacentro')], max_length=20)),
                ('cantidad_de_casos', models.IntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_literal', models.CharField(blank=True, max_length=255)),
                ('monto_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_unitario_literal', models.CharField(blank=True, max_length=255)),
                ('comision_1', models.CharField(choices=[('Titular 1', 'Titular 1'), ('Titular 2', 'Titular 2'), ('Titular 3', 'Titular 3')], max_length=55)),
                ('comision_2', models.CharField(choices=[('Titular 1', 'Titular 1'), ('Titular 2', 'Titular 2'), ('Titular 3', 'Titular 3')], max_length=55)),
                ('seguimiento', models.CharField(choices=[('TICS', 'TICS'), ('JAF', 'JAF'), ('Asesoria Legal', 'Asesoria Legal'), ('Administracion', 'Administracion')], default='TICS', max_length=20)),
                ('nro_grupo', models.IntegerField(default=0)),
                ('nro_preventivo', models.IntegerField(default=0)),
                ('rupe', models.BooleanField(default=False)),
                ('memorandum_comision', models.IntegerField(default=0)),
                ('fecha_memorandum', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('postulante', 'Postulante'), ('seleccionado', 'Seleccionado'), ('contratado', 'Contratado'), ('sin_firmar_contrato', 'Sin Firmar Contrato'), ('renuncia', 'Renuncia')], default='postulante', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.proceso')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estacion', models.CharField(max_length=100, unique=True)),
                ('asignada', models.BooleanField(default=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('defectuoso', 'Defectuoso'), ('contingencia', 'Contingencia'), ('reparacion', 'En Reparacion'), ('funcional', 'Funcional'), ('nuevo', 'Nuevo')], default='funcional', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.kit')),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.llave')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('postulante', 'Postulante'), ('seleccionado', 'Seleccionado'), ('contratado', 'Contratado'), ('sin_firmar_contrato', 'Sin Firmar Contrato'), ('renuncia', 'Renuncia')], default='postulante', max_length=20)),
                ('tipo_operador', models.CharField(choices=[('Operador Urbano', 'Operador Urbano'), ('Operador Rural', 'Operador Rural')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('firmo_contrato', models.BooleanField(default=False)),
                ('firmo_asesoria', models.BooleanField(default=False)),
                ('firmo_direccion', models.BooleanField(default=False)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.coordinador')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.proceso')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDespliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fue_desplegado', models.BooleanField(default=False)),
                ('llego_destino', models.BooleanField(default=False)),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('contador_inicial_c', models.IntegerField(default=0)),
                ('contador_final_c', models.IntegerField(default=0)),
                ('contador_inicial_r', models.IntegerField(default=0)),
                ('contador_final_r', models.IntegerField(default=0)),
                ('incidencias', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estacion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador')),
            ],
        ),
    ]
