# Generated by Django 5.2.7 on 2025-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='nro_contrato',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='latitud',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='longitud',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='sincronizar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrodespliegue',
            name='destino',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
