# Generated by Django 5.2.7 on 2025-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operador_nro_contrato_registrodespliegue_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodespliegue',
            old_name='latitud',
            new_name='latitud_despliegue',
        ),
        migrations.RenameField(
            model_name='registrodespliegue',
            old_name='longitud',
            new_name='latitud_llegada',
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='longitud_despliegue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='longitud_llegada',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
