# Generated by Django 5.2.7 on 2025-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_rename_latitud_registrodespliegue_latitud_despliegue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='codigo_camara',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_decadactilar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_escaner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_estabilizador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_impresora',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_mouse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_pad_firmas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo_teclado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='mouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kit',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='teclado',
            field=models.BooleanField(default=False),
        ),
    ]
