# Generated by Django 5.2.7 on 2025-11-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_kit_codigo_camara_kit_codigo_decadactilar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('En revision', 'En revision'), ('Listo para clonacion', 'Listo para Clonacion'), ('Clonacion', 'Clonacion'), ('Listo para masterizacion', 'Listo para masterizacion'), ('Masterizacion', 'Masterizacion'), ('Listo para asignar', 'Listo para asignar'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado',
            field=models.CharField(choices=[('defectuoso', 'Defectuoso'), ('contingencia', 'Contingencia'), ('reparacion', 'En Reparacion'), ('funcional', 'Funcional'), ('nuevo', 'Nuevo')], default='funcional', max_length=32),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.kit'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='llave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.llave'),
        ),
    ]
