# Generated by Django 5.2.7 on 2025-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_estacion_fase_alter_estacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llave',
            name='codigo_estacion',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
