# Generated by Django 5.2.7 on 2025-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_llave_codigo_estacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='codigo_estacion',
            new_name='nro_estacion',
        ),
        migrations.RenameField(
            model_name='llave',
            old_name='codigo_estacion',
            new_name='nro_estacion',
        ),
        migrations.AddField(
            model_name='estacion',
            name='codigo_equipo',
            field=models.CharField(blank=True, max_length=56, unique=True),
        ),
    ]
