# Generated by Django 5.2.7 on 2025-11-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_rename_codigo_estacion_estacion_nro_estacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodespliegue',
            old_name='fecha_hora_llegada',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='registrodespliegue',
            old_name='latitud_despliegue',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='registrodespliegue',
            old_name='latitud_llegada',
            new_name='longitud',
        ),
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='fecha_hora_salida',
        ),
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='fue_desplegado',
        ),
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='llego_destino',
        ),
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='longitud_despliegue',
        ),
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='longitud_llegada',
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='descripcion_reporte',
            field=models.CharField(choices=[('Despliegue', 'Despliegue'), ('En camino', 'En camino'), ('Incidencia', 'Incidencia'), ('Llego a destino', 'Llego a destino')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='incidencias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nro_estacion',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Periferico', 'Periferico'), ('Herramiento', 'Herramienta'), ('Insumo', 'Insumo'), ('Accesorio', 'Accesorio')], max_length=32, null=True)),
                ('codigo_item', models.CharField(blank=True, max_length=55, null=True)),
                ('serie_item', models.CharField(blank=True, max_length=55, null=True)),
                ('asignado_operador', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador')),
            ],
        ),
    ]
