# Generated by Django 5.2.7 on 2025-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_rename_fecha_hora_llegada_registrodespliegue_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nro_estacion',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
