# Generated by Django 5.2.7 on 2025-11-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_alter_estacion_nro_estacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nro_estacion',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador'),
        ),
    ]
