# Generated by Django 5.2.7 on 2025-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_estacion_nro_estacion_alter_item_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='modelo_camara',
            field=models.CharField(blank=True, choices=[('CANON 110', 'CANON 110'), ('CANON 150', 'CANON 150')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kit',
            name='modelo_escaner',
            field=models.CharField(blank=True, choices=[('CANON 110', 'CANON 110'), ('CANON 100', 'CANON 100')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kit',
            name='modelo_impresora',
            field=models.CharField(blank=True, choices=[('CANON LPB3000', 'CANON LPB3000'), ('CANON LPB6000', 'CANON LPB6000'), ('BROTHER 2700', 'BROTHER 2700')], max_length=20),
        ),
    ]
