# Generated by Django 5.2.7 on 2025-11-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_alter_kit_modelo_camara_alter_kit_modelo_escaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador'),
        ),
    ]
