# Generated by Django 5.2.7 on 2025-11-11 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_item_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='marca',
        ),
        migrations.AddField(
            model_name='estacion',
            name='tipo_estacion',
            field=models.CharField(blank=True, choices=[('LAPTOP', 'LAPTOP'), ('ESCRITORIO', 'ESCRITORIO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.llave'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='modelo',
            field=models.CharField(blank=True, choices=[('DELL OPTIPLEX 360', 'DELL OPTIPLEX 360'), ('DELL OPTIPLEX 390', 'DELL OPTIPLEX 390'), ('DELL E5500', 'DELL E5500'), ('DELL E5520', 'DELL E5520')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nro_estacion',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
