# Generated by Django 5.2.7 on 2025-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_remove_estacion_marca_estacion_tipo_estacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='estado',
            new_name='estado_computadora',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='kit',
        ),
        migrations.AddField(
            model_name='estacion',
            name='adaptador_3a2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='cable_extensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_camara',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_decadactilar',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_disco_duro',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_escaner',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_estabilizador_energia',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_hub_usb',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_impresora',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_memorias_ram',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_monitor',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_pad_firmas',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_pila_madre',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='etiqueta_kit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='monitor_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='testeo_pila',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tripode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('Revisado', 'Revisado'), ('Listo para clonacion', 'Listo para Clonacion'), ('Clonado', 'Clonado'), ('Listo para masterizacion', 'Listo para masterizacion'), ('Masterizado', 'Masterizado'), ('Listo para asignar', 'Listo para asignar'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipo_estacion',
            field=models.CharField(blank=True, choices=[('FIJA', 'FIJA'), ('MOVIL', 'MOVIL')], max_length=255, null=True),
        ),
    ]
