# Generated by Django 5.2.4 on 2025-11-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_rename_estado_estacion_estado_computadora_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='etiqueta_kit',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='firmo_asesoria',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='firmo_contrato',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='firmo_direccion',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='nro_contrato',
        ),
        migrations.AlterField(
            model_name='operador',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.coordinador'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.estacion'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.ruta'),
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
    ]
