# Generated by Django 5.2.4 on 2025-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_delete_kit_remove_coordinador_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='fecha_reporte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
