# Generated by Django 5.2.4 on 2025-11-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_reportediario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='clonado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='masterizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='recepcionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('En Revision', 'En Revision'), ('Revisado funcional', 'Revisado funcional'), ('En Clonacion', 'En Clonacion'), ('En Masterizacion', 'En Masterizacion'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
    ]
