# Generated by Django 5.2.7 on 2025-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_estacion_asignado_estacion_clonado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='estado',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='sincronizar',
            field=models.BooleanField(default=False),
        ),
    ]
