# Generated by Django 5.2.7 on 2025-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_reportediario_estado_reportediario_sincronizar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('En Revision', 'En Revision'), ('Revisado funcional', 'Revisado funcional'), ('En Clonacion', 'En Clonacion'), ('Clonado', 'Clonado'), ('En Masterizacion', 'En Masterizacion'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('Desplegado', 'Desplegado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
    ]
