# Generated by Django 5.2.7 on 2025-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0019_alter_estacion_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='registro_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='registro_r',
            field=models.IntegerField(default=0),
        ),
    ]
