# Generated by Django 5.2.7 on 2025-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0020_reportediario_registro_c_reportediario_registro_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='estado_regulador_voltaje',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_teclado',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=24),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_camara',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_computadora',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_decadactilar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_disco_duro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_escaner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_estabilizador_energia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_hub_usb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_impresora',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_memorias_ram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_monitor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_pad_firmas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_pila_madre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_regulador_voltaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_teclado',
            field=models.TextField(blank=True),
        ),
    ]
