# Generated by Django 5.2.7 on 2025-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_estacion_estado_regulador_voltaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='modelo_camara',
            field=models.CharField(blank=True, choices=[('CANON SX 110', 'CANON SX 110'), ('CANON SX 150', 'CANON SX 150')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='modelo_escaner',
            field=models.CharField(blank=True, choices=[('CANON Lide 100', 'CANON Lide 100'), ('CANON Lide 110', 'CANON Lide 110')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='modelo_impresora',
            field=models.CharField(blank=True, choices=[('CANON LPB 3000', 'CANON LPB 3000'), ('CANON LPB 6000', 'CANON LPB 6000'), ('CANON IP 1900', 'CANON IP 1900'), ('CANON IP 2700', 'CANON IP 2700'), ('BROTHER 2100', 'BROTHER 2100')], max_length=50, null=True),
        ),
    ]
