# Generated by Django 5.2.7 on 2025-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0022_estacion_modelo_camara_estacion_modelo_escaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nro_estacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
