# Generated by Django 5.2.7 on 2025-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0023_alter_estacion_nro_estacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='modelo_impresora',
            field=models.CharField(blank=True, choices=[('CANON LPB 3000', 'CANON LPB 3000'), ('CANON LPB 6000', 'CANON LPB 6000'), ('CANON IP 1900', 'CANON IP 1900'), ('CANON IP 2700', 'CANON IP 2700'), ('CANON IP 2702', 'CANON IP 2702'), ('BROTHER 2100', 'BROTHER 2100')], max_length=50, null=True),
        ),
    ]
