# Generated by Django 5.2.7 on 2025-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0024_alter_estacion_modelo_impresora'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='obs_adaptador_3a2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_banner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_cable_extensor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='obs_tripode',
            field=models.TextField(blank=True),
        ),
    ]
