# Generated by Django 5.2.7 on 2025-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0025_estacion_obs_adaptador_3a2_estacion_obs_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='contador_final_c',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='contador_final_r',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='contador_inicial_c',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='contador_inicial_r',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
