# Generated by Django 5.2.7 on 2025-11-19 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0026_alter_reportediario_contador_final_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEmpadronamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='operador',
            name='carnet',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='tipo_operador',
            field=models.CharField(choices=[('URBANO', 'OPERADOR URBANO'), ('RURAL', 'OPERADOR RURAL')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='centro_empadronamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.centroempadronamiento'),
        ),
        migrations.CreateModel(
            name='UbicacionesOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(blank=True, max_length=255, null=True)),
                ('longitud', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador')),
            ],
        ),
    ]
