# Generated by Django 5.2.7 on 2025-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0027_centroempadronamiento_operador_carnet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centroempadronamiento',
            old_name='nombre',
            new_name='punto_de_empadronamiento',
        ),
        migrations.AlterField(
            model_name='centroempadronamiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='centroempadronamiento',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centroempadronamiento',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
