# Generated by Django 5.2.7 on 2025-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_load_puntos_empadronamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='estado_camara',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_decadactilar',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_disco_duro',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_escaner',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_estabilizador_energia',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_hub_usb',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_impresora',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_memorias_ram',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_monitor',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_pad_firmas',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_pila_madre',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_regulador_voltaje',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado_teclado',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24),
        ),
    ]
