# Generated by Django 5.2.7 on 2025-11-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0030_alter_estacion_estado_camara_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodespliegue',
            name='destino',
        ),
        migrations.AddField(
            model_name='registrodespliegue',
            name='centro_empadronamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.centroempadronamiento'),
        ),
    ]
