# Generated by Django 5.2.7 on 2025-11-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0031_remove_registrodespliegue_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroempadronamiento',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centroempadronamiento',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
