# Generated by Django 5.2.7 on 2025-11-21 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0032_centroempadronamiento_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('Revisado con Observacion', 'Revisado con Observacion'), ('Revisado funcional', 'Revisado funcional'), ('En Clonacion', 'En Clonacion'), ('Clonado', 'Clonado'), ('En Masterizacion', 'En Masterizacion'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('Desplegado', 'Desplegado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.llave', unique=True),
        ),
    ]
