# Generated by Django 5.2.7 on 2025-11-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0033_alter_estacion_fase_alter_estacion_llave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.llave'),
        ),
    ]
