# Generated by Django 5.2.7 on 2025-11-22 15:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0034_alter_estacion_llave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEstacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_equipo', models.CharField(blank=True, db_index=True, max_length=56)),
                ('nro_estacion', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo_estacion', models.CharField(blank=True, choices=[('FIJA', 'FIJA'), ('MOVIL', 'MOVIL')], max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, choices=[('DELL OPTIPLEX 360', 'DELL OPTIPLEX 360'), ('DELL OPTIPLEX 390', 'DELL OPTIPLEX 390'), ('DELL E5500', 'DELL E5500'), ('DELL E5520', 'DELL E5520')], max_length=255, null=True)),
                ('fase', models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('Revisado con Observacion', 'Revisado con Observacion'), ('Revisado funcional', 'Revisado funcional'), ('En Clonacion', 'En Clonacion'), ('Clonado', 'Clonado'), ('En Masterizacion', 'En Masterizacion'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('Desplegado', 'Desplegado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56)),
                ('estado_computadora', models.CharField(choices=[('defectuoso', 'Defectuoso'), ('contingencia', 'Contingencia'), ('reparacion', 'En Reparacion'), ('funcional', 'Funcional'), ('nuevo', 'Nuevo')], default='funcional', max_length=32)),
                ('estado_monitor', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_escaner', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('modelo_escaner', models.CharField(blank=True, choices=[('CANON Lide 100', 'CANON Lide 100'), ('CANON Lide 110', 'CANON Lide 110')], max_length=50, null=True)),
                ('estado_impresora', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('modelo_impresora', models.CharField(blank=True, choices=[('CANON LPB 3000', 'CANON LPB 3000'), ('CANON LPB 6000', 'CANON LPB 6000'), ('CANON IP 1900', 'CANON IP 1900'), ('CANON IP 2700', 'CANON IP 2700'), ('CANON IP 2702', 'CANON IP 2702'), ('BROTHER 2100', 'BROTHER 2100')], max_length=50, null=True)),
                ('estado_pad_firmas', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_camara', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('modelo_camara', models.CharField(blank=True, choices=[('CANON SX 110', 'CANON SX 110'), ('CANON SX 150', 'CANON SX 150')], max_length=50, null=True)),
                ('estado_decadactilar', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_hub_usb', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_estabilizador_energia', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_pila_madre', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_memorias_ram', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_disco_duro', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('cable_extensor', models.BooleanField(default=False)),
                ('tripode', models.BooleanField(default=False)),
                ('banner', models.BooleanField(default=False)),
                ('adaptador_3a2', models.BooleanField(default=False)),
                ('monitor_pc', models.BooleanField(default=False)),
                ('testeo_pila', models.BooleanField(default=False)),
                ('asignada', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('recepcionado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('clonado', models.BooleanField(default=False)),
                ('masterizado', models.BooleanField(default=False)),
                ('asignado', models.BooleanField(default=False)),
                ('estado_teclado', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('estado_regulador_voltaje', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('No tiene', 'No Tiene')], default='Buena', max_length=24)),
                ('obs_computadora', models.TextField(blank=True)),
                ('obs_monitor', models.TextField(blank=True)),
                ('obs_escaner', models.TextField(blank=True)),
                ('obs_impresora', models.TextField(blank=True)),
                ('obs_pad_firmas', models.TextField(blank=True)),
                ('obs_camara', models.TextField(blank=True)),
                ('obs_decadactilar', models.TextField(blank=True)),
                ('obs_hub_usb', models.TextField(blank=True)),
                ('obs_estabilizador_energia', models.TextField(blank=True)),
                ('obs_pila_madre', models.TextField(blank=True)),
                ('obs_memorias_ram', models.TextField(blank=True)),
                ('obs_disco_duro', models.TextField(blank=True)),
                ('obs_teclado', models.TextField(blank=True)),
                ('obs_regulador_voltaje', models.TextField(blank=True)),
                ('obs_cable_extensor', models.TextField(blank=True)),
                ('obs_tripode', models.TextField(blank=True)),
                ('obs_banner', models.TextField(blank=True)),
                ('obs_adaptador_3a2', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('llave', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.llave')),
            ],
            options={
                'verbose_name': 'historical estacion',
                'verbose_name_plural': 'historical estacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
