# Generated by Django 5.2.7 on 2025-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_historicalestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('Revisado con Observacion', 'Revisado con Observacion'), ('Revisado funcional', 'Revisado funcional'), ('Clonado', 'Clonado'), ('Llave asignada', 'Llave asignada'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('Desplegado', 'Desplegado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
        migrations.AlterField(
            model_name='historicalestacion',
            name='fase',
            field=models.CharField(choices=[('Recepcionado', 'Recepcionado'), ('Revisado con Observacion', 'Revisado con Observacion'), ('Revisado funcional', 'Revisado funcional'), ('Clonado', 'Clonado'), ('Llave asignada', 'Llave asignada'), ('Masterizado', 'Masterizado'), ('Asignado', 'Asignado'), ('Desplegado', 'Desplegado'), ('En mantenimiento', 'En mantenimiento')], default='Recepcionado', max_length=56),
        ),
    ]
