# Generated by Django 5.2.7 on 2025-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_alter_estacion_fase_alter_historicalestacion_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='tipo_operador',
            field=models.CharField(choices=[('Operador Urbano', 'OPERADOR URBANO'), ('Operador Rural', 'OPERADOR RURAL')], max_length=20),
        ),
    ]
