# Generated by Django 5.2.7 on 2025-12-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0038_remove_coordinador_ruta_ruta_coordinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='brigada_movil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='megacentro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.megacentro'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.ruta'),
        ),
        migrations.AddField(
            model_name='historicalestacion',
            name='brigada_movil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestacion',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestacion',
            name='megacentro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.megacentro'),
        ),
        migrations.AddField(
            model_name='historicalestacion',
            name='ruta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.ruta'),
        ),
    ]
