# Generated by Django 5.2.7 on 2025-12-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0039_estacion_brigada_movil_estacion_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centroempadronamiento',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='historicalestacion',
            name='ruta',
        ),
        migrations.AddField(
            model_name='centroempadronamiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centroempadronamiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centroempadronamiento',
            name='movimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centroempadronamiento',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.ruta'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='centro_empadronamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.centroempadronamiento'),
        ),
        migrations.AddField(
            model_name='historicalestacion',
            name='centro_empadronamiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.centroempadronamiento'),
        ),
    ]
