# Generated by Django 5.2.7 on 2025-12-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0041_alter_centroempadronamiento_movimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiarioLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_formulario_faltantes', models.IntegerField(blank=True, default=0, null=True)),
                ('r_inicial', models.IntegerField(default=0)),
                ('r_final', models.IntegerField(default=0)),
                ('obervaciones_counter_r', models.TextField(blank=True, null=True)),
                ('c_inicial', models.IntegerField(default=0)),
                ('c_final', models.IntegerField(default=0)),
                ('observaciones_c', models.TextField(blank=True, null=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estacion')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.operador')),
            ],
        ),
    ]
