# Generated by Django 5.2.7 on 2025-12-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0042_reportediariologistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediariologistico',
            name='fecha_reporte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
