# Generated by Django 5.2.7 on 2025-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0043_reportediariologistico_fecha_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportediariologistico',
            name='estacion',
        ),
        migrations.AddField(
            model_name='reportediariologistico',
            name='nro_estacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
