# Generated by Django 5.2.7 on 2025-12-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0044_remove_reportediariologistico_estacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='entregaBackup',
            field=models.BooleanField(default=False),
        ),
    ]
