# Generated by Django 5.2.7 on 2025-12-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0045_operador_entregabackup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='entregaBackup',
            new_name='entrega_backup',
        ),
    ]
